env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - simple-import-sort
  - import
settings:
  react:
    version: detect
rules:
  react/react-in-jsx-scope: off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    rules:
      simple-import-sort/imports:
        - warn
        - groups:
            # Packages `react` related packages come first.
            - [^react, ^@?\w+]
            # Internal packages.
            - [^(@|components)(/.*|$)]
            # Side effect imports.
            - [^\u0000]
            # Parent imports. Put `..` last.
            - [^\.\.(?!/?$), ^\.\./?$]
            # Other relative imports. Put same-folder imports and `.` last.
            - [^\./(?=.*/)(?!/?$), ^\.(?!/?$), ^\./?$]
            # Style imports.
            - [^.+\.?(css)$]
